/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Measurements(
    val id: Int? = null,
    val timestamp: LocalDateTime? = null,
    val temperature: Double? = null,
    val humidity: Double? = null,
    val ipAddress: String? = null,
    val macAddress: String? = null,
    val deviceName: String? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Measurements = other as Measurements
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.timestamp == null) {
            if (o.timestamp != null)
                return false
        }
        else if (this.timestamp != o.timestamp)
            return false
        if (this.temperature == null) {
            if (o.temperature != null)
                return false
        }
        else if (this.temperature != o.temperature)
            return false
        if (this.humidity == null) {
            if (o.humidity != null)
                return false
        }
        else if (this.humidity != o.humidity)
            return false
        if (this.ipAddress == null) {
            if (o.ipAddress != null)
                return false
        }
        else if (this.ipAddress != o.ipAddress)
            return false
        if (this.macAddress == null) {
            if (o.macAddress != null)
                return false
        }
        else if (this.macAddress != o.macAddress)
            return false
        if (this.deviceName == null) {
            if (o.deviceName != null)
                return false
        }
        else if (this.deviceName != o.deviceName)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.timestamp == null) 0 else this.timestamp.hashCode())
        result = prime * result + (if (this.temperature == null) 0 else this.temperature.hashCode())
        result = prime * result + (if (this.humidity == null) 0 else this.humidity.hashCode())
        result = prime * result + (if (this.ipAddress == null) 0 else this.ipAddress.hashCode())
        result = prime * result + (if (this.macAddress == null) 0 else this.macAddress.hashCode())
        result = prime * result + (if (this.deviceName == null) 0 else this.deviceName.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Measurements (")

        sb.append(id)
        sb.append(", ").append(timestamp)
        sb.append(", ").append(temperature)
        sb.append(", ").append(humidity)
        sb.append(", ").append(ipAddress)
        sb.append(", ").append(macAddress)
        sb.append(", ").append(deviceName)

        sb.append(")")
        return sb.toString()
    }
}
