@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.benlukka.jooq.keys


import jooq.tables.Measurements
import jooq.tables.records.MeasurementsRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val MEASUREMENTS_PKEY: UniqueKey<MeasurementsRecord> = Internal.createUniqueKey(
    Measurements.MEASUREMENTS, DSL.name("measurements_pkey"), arrayOf(
        Measurements.MEASUREMENTS.ID), true)
